Access/Change specific elements rows colums etc

In [19]:
import numpy as np

In [20]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
a.shape

(2, 7)

In [22]:
# get specific element [r,c]

print(a[1,-2])

13


In [23]:
# get a pecific row
a[0, : ]

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
# get a specific column
a[:,6]

array([ 7, 14])

In [25]:
a[0,1:6:2]

array([2, 4, 6])

In [26]:
print(a)
a[1,5] = 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12  5 14]]


In [27]:
# 3d array
b = np.array([[[1,2],[3,4],[5,6]]])

In [28]:
b.ndim

3

In [30]:
b[0,1,0]

3