In [9]:
import numpy as np

In [10]:
a = np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [11]:
b = np.array([[9,8,7],[6,5,4]])
print(b)

[[9 8 7]
 [6 5 4]]


In [12]:
# getdimension

a.ndim

1

In [13]:
# get shape
b.shape

(2, 3)

In [14]:
# get memory and type

a.dtype

dtype('int16')

In [15]:
a.itemsize

2

In [16]:
a.nbytes

6