In [1]:
# types of array initialization

import numpy as np

In [3]:
# initialize zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
# initialize ones
np.ones((4,2,2),dtype="int16")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [5]:
# initialize any other number
np.full((2,2),9)

array([[9, 9],
       [9, 9]])

In [6]:
# full like method
a = np.array([[1,2,3],[4,5,6]])
np.full(a.shape,4)

array([[4, 4, 4],
       [4, 4, 4]])

In [9]:
# random nos
np.random.rand(4,2)
np.random.random_sample((4,2))


array([[0.3798459 , 0.61976225],
       [0.32224431, 0.06058792],
       [0.96438999, 0.8284603 ],
       [0.26407283, 0.85850823]])

In [11]:
# random integer values
np.random.randint(7,size=(3,3))

array([[2, 3, 6],
       [3, 5, 4],
       [3, 2, 6]])

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
